POST http://localhost:3000/api/notes 
Content-Type: application/json

{
    "content" : "segunda nota por ruta" ,
    "important" : true
}
      
###
//aqui es una peticion fallida 
      POST http://localhost:3000/api/notes 
Content-Type: application/json

{
  
    "important" : true
}
      